apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: postgres
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.5.7
    chart: postgresql
    helm:
      valuesObject:
        auth:
          enablePostgresUser: true
          postgresPassword: "postgres"  # In production, use a secretGenerator or external secret
        primary:
          service:
            type: LoadBalancer
            ports:
              postgresql: 5432
        persistence:
          size: 8Gi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true