apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: metrics
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://victoriametrics.github.io/helm-charts/
    targetRevision: 0.42.0
    chart: victoria-metrics-k8s-stack
    helm:
      valuesObject:
        nameOverride: "vm"
        fullnameOverride: "vm"
        # Default values for Victoria Metrics Stack
        # Modified based on https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/values.yaml
        kubeApiServer:
          enabled: true
        
        # Enable default ServiceMonitors
        kubelet:
          enabled: true
        kubeControllerManager:
          enabled: true
        coreDns:
          enabled: true
        kubeEtcd:
          enabled: false
        kubeScheduler:
          enabled: true
        kubeProxy:
          enabled: true
          
        # Configure Victoria Metrics components
        victoria-metrics-operator:
          enabled: true
        
        # Add VMAgent for metrics collection
        vmagent:
          enabled: true
          spec:
            serviceScrapeNamespaceSelector: {}
            serviceScrapeSelector: {}
            podScrapeNamespaceSelector: {}
            podScrapeSelector: {}
            probeNamespaceSelector: {}
            probeSelector: {}
            staticScrapeNamespaceSelector: {}
            staticScrapeSelector: {}
            replicaCount: 1
            resources:
              requests:
                memory: "256Mi"
                cpu: "200m"
              limits:
                memory: "512Mi"
                cpu: "400m"
        
        # Enable VMSingle for metrics storage
        vmsingle:
          enabled: true
          spec:
            retentionPeriod: "30d"
            resources:
              requests:
                memory: "1Gi" 
                cpu: "250m"
              limits:
                memory: "2Gi"
                cpu: "500m"
            storage:
              accessModes:
                - ReadWriteOnce
              size: 10Gi
        
        # Disable VMCluster as we're using VMSingle instead
        vmcluster:
          enabled: false
        
        vmalert:
          enabled: true
          spec:
            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "256Mi"
                cpu: "200m"
        
        # Configure Grafana with dashboards
        grafana:
          enabled: false
        # Alert manager for handling notifications
        alertmanager:
          enabled: true
          spec:
            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "256Mi"
                cpu: "200m"
        
        defaultRules:
          create: true
          rules:
            alertmanager: true
            etcd: true
            general: true
            k8s: true
            kubeApiserver: true
            kubePrometheusNodeAlerting: true
            kubePrometheusNode: true
            kubernetesAbsent: true
            kubernetesApps: true
            kubernetesResources: true
            kubernetesStorage: true
            kubernetesSystem: true
            prometheus: true
            vmagent: true
            vmalert: true
            vmcluster: true
            vmsingle: true
        
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true